#!/bin/bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

# Check if the image already exists
if [ grep -q hughfletcher/mysql1 /var/lib/docker/repositories-aufs ]; then
  echo "-----> building mysql"
  if [[ $DOKKU_TRACE ]]; then
    docker build -t hughfletcher/mysql github.com/hughfletcher/dokku-mysql-dockerfiles
  else
    docker build -q=true -t hughfletcher/mysql github.com/hughfletcher/dokku-mysql-dockerfiles
  fi
fi
